# Generated by Django 4.1.7 on 2023-05-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_history_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='unpaid',
        ),
    ]
