# Generated by Django 4.2 on 2023-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='in_worksheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='worksheet_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
