# Generated by Django 4.2 on 2023-07-09 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_customer_in_worksheet_customer_worksheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='non_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_category', models.TextField(choices=[('fuel', 'Fuel'), ('business_equipment', 'Business Equipment'), ('water', 'Water'), ('vehicle_costs', 'Vehicle Costs'), ('other', 'Other...')])),
                ('expense_name', models.TextField()),
                ('cost', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
